The Foundation of Scientific Python
===
NumPy (Numerical Python) is the fundamental package for numerical computing in Python. At its core, it introduces the ndarray — a powerful N-dimensional array object that is dramatically faster and more memory-efficient than Python's built-in lists.

In [1]:
# Why NumPy for Data Analysis?
# Speed: NumPy operations run 10–100× faster than pure Python loops on numerical data.
# Memory efficiency: A NumPy array of 1 million integers uses ~8 MB; a Python list uses ~35 MB.
# Expressive syntax: Operations like "multiply every price by 1.1" are one-liners.
# Foundation of the ecosystem: Pandas, Matplotlib, Scikit-learn, and TensorFlow all build on NumPy arrays.
# Rich statistical functions: mean, median, std, percentile — all built in.


Python — why NumPy is faster
===

In [4]:
import numpy as np
import time

# create one million number
data_list=list(range(1_000_000))
data_np=np.arange(1_000_000)

# python list loop aproach 
t1=time.time()
result=[x**2 for x in data_list]
print(f"pyhton list {time.time() -t1:.4f}s")

# numpay vectorze approach 
t2 = time.time()
result = data_np * 2
print(f"NumPy array: {time.time() - t2:.4f}s")   

pyhton list 0.0858s
NumPy array: 0.0144s


1D array
===

In [7]:
import numpy as np

# creating 1d array 
arr1=np.array([1,2,3,4,5,6])
# arr1
arr2=np.array({1,2,3,4,5})
# arr2

print(f"arr1:{arr1}, arr2{arr2} and there types arr1:{type(arr1)} , arr2:{type(arr2)}")

arr1:[1 2 3 4 5 6], arr2{1, 2, 3, 4, 5} and there types arr1:<class 'numpy.ndarray'> , arr2:<class 'numpy.ndarray'>


In [13]:
# shape the array 
arr1.shape
# arr2.shape

(6,)

In [21]:
# reshape
arr3=np.array([5,6,7,8,9,10])
arr3.reshape(2,3)


array([[ 5,  6,  7],
       [ 8,  9, 10]])

2D array
===

In [87]:
# creating 2d array 

Arr=np.array([[1,2,3,4,5,6],[10,11,12,13,14,15,],[66,55,44,33,22,11]])
print(Arr)
Arr.shape

Arr.nbytes

[[ 1  2  3  4  5  6]
 [10 11 12 13 14 15]
 [66 55 44 33 22 11]]


144

In [86]:
marks=np.array([
    [45,67,89,35,88,96,],
    [30,34,76,54,78,90],
    [56,98,78,66,77,88]
])

print(marks)
print(marks.ndim)
print(marks.size)

[[45 67 89 35 88 96]
 [30 34 76 54 78 90]
 [56 98 78 66 77 88]]
2
18


# ── Useful creation functions 



In [67]:
# the function give us a complete matrixs 

# zeros 
np.zeros((3,4))
# np.zeros((5,4))
# np.zeros((1,4))



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
# ones : give us 1 : the matrix all of one

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
# full 
#   / use for filling the matrix with elementa 
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [70]:
# Arrange  : sequence full the sequence with the given 3rd para meter 

np.arange(3,80,5)

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78])

In [76]:
# line-space?

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [83]:
# identical matrix 
# eye

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Random arrays (very common in data science)
===

In [84]:
rng = np.random.default_rng(42)     # seed for reproducibility
sales = rng.integers(100, 500, size=30)  # 30 random sales figures

print(sales)


[135 409 361 275 273 443 134 378 180 137 310 490 394 404 386 414 305 151
 435 280 300 248 173 470 412 357 260 429 318 277]


240

Element-wise operations===
addition, subtraction, multiplication, division

In [91]:
arr=np.array([1,2,3,4])
arr2=np.array([6,7,8,90])

# element wise aditoin
arr+arr2

arr-arr2
arr*arr2
arr/arr2

array([0.16666667, 0.28571429, 0.375     , 0.04444444])

Univeral functions
===

In [96]:
arr=np.array([1, 2,3])

# squareroot
print(np.sqrt(arr))

# square
print(np.square(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.         1.41421356 1.73205081]
[1 4 9]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]



Indexing & Slicing
===

Getting Exactly the Data You Need

In real analysis, you rarely need the whole dataset at once. Indexing lets you grab specific rows, columns, or elements. NumPy's slicing syntax is [start:stop:step] — same as Python lists, but extended to multiple dimensions.

2D Indexing: scores[row, column]


In [121]:
score=np.array([[1,3,4,5],[45,67,88,5],[7,23,76,89]])
print(score)

print('------')

# slicing and indexing
print(score[1:])
print('-----')

print(score[2:])

[[ 1  3  4  5]
 [45 67 88  5]
 [ 7 23 76 89]]
------
[[45 67 88  5]
 [ 7 23 76 89]]
-----
[[ 7 23 76 89]]


Python — indexing & slicing


In [131]:
scores = np.array([
    [85, 92, 78, 96],
    [70, 88, 91, 65],
    [55, 72, 68, 80],
])

# basic indexing 
print(scores[0,2])
print(scores[1])
print(scores[0:,1])

78
[70 88 91 65]
[92 88 72]


# ── Slicing ───
slicing is a way to grab a range of values from an array. It uses the syntax [start:stop:step], where start is the index to begin at, stop is the index to end before, and step is how many indices to skip. For example, arr[1:5] grabs indices 1 through 4, while arr[::2] grabs every other element.
---87----

indexing is a way to grab specific values from an array. It uses the syntax [index1, index2, ...], where each index corresponds to a dimension of the array. For example, arr[0] grabs the first element of a 1D array, while arr[0, 1] grabs the element in the first row and second column of a 2D array.

In [143]:
#  Slicing
print(scores)

scores[0:2,1:3]  # rows 0-1, cols 1-2 → [[92,78],[88,91]]

scores[:,1:3] # all rows, cols 1 and 2

scores[::2]   # every other row
print('------------')
scores[:, ::-1]   # reverse column order



[[85 92 78 96]
 [70 88 91 65]
 [55 72 68 80]]
------------


array([[96, 78, 92, 85],
       [65, 91, 88, 70],
       [80, 68, 72, 55]])

In [155]:
# ── Boolean (Fancy) Indexing — very powerful! ──────

marks = np.array([45, 82, 59, 90, 71, 38, 95])

# Who passed? (marks >= 60)
passed=marks[marks>60]
print(passed)

# Who scored between 60 and 85?
scored=marks[(marks>=60) & (marks<=85)]
print(scored)

# Replace failing marks with 0 (data cleaning!)

marks[marks<60]=0
print(marks)

# ── Fancy indexing with arrays ─

prices = np.array([200, 450, 125, 780, 310])
selected = prices[[0, 2, 4]] 
print(selected)

[82 90 71 95]
[82 71]
[ 0 82  0 90 71  0 95]
[200 125 310]



Data Types (dtype)
===
Why Data Types Matter in Analysis

Every NumPy array has a single data type (dtype). Unlike Python where a list can hold mixed types, NumPy arrays are homogeneous — all elements share one type. This is what makes them fast, but you need to choose types wisely.



In [172]:
# Python — working with dtypes

a=np.array([1,4,56,7])
print(a.dtype)
b=np.array([1,2,3,4], dtype=np.float64)
print(b.dtype)

int64
float64


# ── Type conversion (casting) ──────────────────────


In [178]:
prices=np.array([19.9, 13.8, 44.9, 24.3, 32.5])

int_prices=prices.astype(np.int32)
print(int_prices)


[19 13 44 24 32]


# ── Real example: memory saving ───────────────────


In [185]:
large = np.random.randint(0, 255, size=(1000, 1000))

print(large.nbytes)

small=large.astype(np.int8)
print(small.nbytes)

4000000
1000000


In [187]:
# # ── Watch out for integer overflow! ───────────────
# x = np.array([200], dtype=np.int8)
# print(x + 100)  # [-44]  ← 300 overflows int8 range!

⚡Array Operations
===

Vectorized Math — No Loops Needed

The power of NumPy is that you can apply operations to entire arrays at once. An operation like prices * 1.1 applies the multiplication to every element simultaneously — this is called vectorization.

In [198]:
# Python — mathematical operations

sales = np.array([1200, 1450, 980, 2100, 1750, 890])

# ── Element-wise arithmetic ────────────────────────
sales+4
sales*3
sales-5

sales/4

np.sqrt(sales)

np.square(sales)


array([1440000, 2102500,  960400, 4410000, 3062500,  792100])

In [207]:
# ── Two arrays: element-wise ───────────────────────
cost   = np.array([800, 900, 600, 1500, 1000, 500])
profit=sales-cost
print(sales)
print(cost)
print(profit)

margin = (profit / sales) * 100   # profit margin %
print(np.round(margin, 1))  

[1200 1450  980 2100 1750  890]
[ 800  900  600 1500 1000  500]
[400 550 380 600 750 390]
[33.3 37.9 38.8 28.6 42.9 43.8]


Python — statistical operations (the heart of data analysis)
===

In [219]:
marks = np.array([[85, 92, 78, 96],
                    [70, 88, 91, 65],
                    [55, 72, 68, 80]])
# ── Global statistics ──────────────────────────────
print(marks)
print(np.mean(marks))       # 78.33 — overall class average
print(np.median(marks))     # 80.0
print(np.std(marks))        # standard deviation
print(np.min(marks))        # 55 — lowest score overall
print(np.max(marks))        # 96 — highest score
print(np.percentile(marks, 75))  # 75th percentile = 90.25

[[85 92 78 96]
 [70 88 91 65]
 [55 72 68 80]]
78.33333333333333
79.0
12.036980056845191
55
96
88.75


In [220]:
# ── Axis-based statistics (super useful!) ──────────
# axis=0 → collapse rows (result per COLUMN = per subject)
subject_avg = np.mean(marks, axis=0)
print(subject_avg)   # [70.0, 84.0, 79.0, 80.3] — avg per subject

# axis=1 → collapse columns (result per ROW = per student)
student_avg = np.mean(marks, axis=1)
print(student_avg)   # [87.75, 78.5, 68.75] — avg per student

# ── Finding positions ──────────────────────────────
print(np.argmax(student_avg))  # 0 — student 0 has highest avg
print(np.argsort(student_avg)) # [2, 1, 0] — sorted ranking

# ── Cumulative operations ──────────────────────────
monthly_sales = np.array([100, 150, 120, 200])
print(np.cumsum(monthly_sales)) # [100, 250, 370, 570] — running total

[70.         84.         79.         80.33333333]
[87.75 78.5  68.75]
0
[2 1 0]
[100 250 370 570]


Broadcasting 
====
Operations Between Arrays of Different Shapes

Broadcasting is NumPy's mechanism for performing operations on arrays with different shapes — without copying data. It's one of NumPy's most powerful (and initially confusing) features.

The rule: Arrays are compatible if, starting from the trailing dimensions, their sizes either match or one of them is 1.

In [ ]:
# # Example: Subtract the column mean from each row
# marks shape: (3, 4) ← 3 students, 4 subjects
# col_mean shape: (1, 4) → (3, 4) ← broadcast across rows

![alt text](image.png)

In [230]:
scores = np.array([[85, 92, 78, 96],
                    [70, 88, 91, 65],
                    [55, 72, 68, 80]])  # shape (3, 4)

# ── Scalar broadcasting (simplest) ────────────────
scores_scaled = scores * 1.1   # scalar → broadcast to (3,4)

# ── Row vector: normalize each subject ────────────
col_mean = np.mean(scores, axis=0)    # shape (4,)
centered = scores - col_mean           # (3,4) - (4,) → works!

# ── Column vector: subtract each student's avg ────
row_mean = np.mean(scores, axis=1, keepdims=True)  # shape (3,1) ← KEY!
deviation = scores - row_mean              # (3,4) - (3,1) → works!
print(deviation)  # how far each score is from that student's mean

# ── Practical: apply different bonuses per subject ─
subject_weights = np.array([0.3, 0.3, 0.2, 0.2])  # (4,)
weighted_scores = scores * subject_weights          # (3,4) × (4,)
final_grade     = weighted_scores.sum(axis=1)        # (3,)
print(final_grade)  # [87.4, 79.7, 68.7]

[[ -2.75   4.25  -9.75   8.25]
 [ -8.5    9.5   12.5  -13.5 ]
 [-13.75   3.25  -0.75  11.25]]
[87.9 78.6 67.7]


In [231]:
# ── reshape ────────────────────────────────────────
flat    = np.arange(12)             # [0,1,2,...,11] shape (12,)
matrix  = flat.reshape(3, 4)        # shape (3,4)
cube    = flat.reshape(2, 2, 3)     # shape (2,2,3)
auto    = flat.reshape(3, -1)       # -1 = "figure it out" → (3,4)
col     = flat.reshape(-1, 1)      # (12,1) → column vector

# ── flatten vs ravel ───────────────────────────────
matrix.flatten()   # returns a COPY: always 1D
matrix.ravel()     # returns a VIEW when possible: faster

# ── transpose ──────────────────────────────────────
data = np.array([[1, 2, 3],
                  [4, 5, 6]])    # shape (2, 3)
data.T                            # shape (3, 2) — rows ↔ columns

# ── stacking & splitting ───────────────────────────
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack([a, b])   # [[1,2,3],[4,5,6]] — stack as rows
np.hstack([a, b])   # [1,2,3,4,5,6] — concatenate horizontally
np.column_stack([a, b])  # [[1,4],[2,5],[3,6]] — as 2 columns

# ── Real use case: prepare features for ML ─────────
age    = np.array([25, 32, 41, 28])
salary = np.array([40000, 65000, 90000, 50000])
X = np.column_stack([age, salary])  # (4, 2) feature matrix
print(X.shape)                          # (4, 2) — ready for sklearn!

(4, 2)


Mini project 
===

Student Examination Analysis System

You've been given marks data for 8 students across 5 subjects. Your task is to build a complete analysis pipeline using only NumPy — calculate stats, assign grades, identify top performers, and normalize scores.

In [232]:
import numpy as np

# ════════════════════════════════════════════════
# DATASET: 8 students × 5 subjects
# Subjects: Math, Physics, Chemistry, CS, English
# ════════════════════════════════════════════════
marks = np.array([
    [88, 76, 91, 95, 82],   # Ali
    [72, 85, 68, 90, 77],   # Sara
    [55, 60, 48, 70, 65],   # Hamza
    [95, 92, 88, 98, 91],   # Ayesha
    [40, 38, 55, 45, 52],   # Usman
    [78, 82, 75, 80, 88],   # Zara
    [65, 70, 72, 60, 68],   # Bilal
    [82, 88, 85, 79, 90],   # Fatima
], dtype=np.float64)

students = ["Ali", "Sara", "Hamza", "Ayesha",
            "Usman", "Zara", "Bilal", "Fatima"]
subjects = ["Math", "Physics", "Chem", "CS", "Eng"]

# ── STEP 1: Basic Statistics ──────────────────────
student_avg  = np.mean(marks, axis=1)     # per student
student_max  = np.max(marks, axis=1)
student_min  = np.min(marks, axis=1)
student_std  = np.std(marks, axis=1)
subject_avg  = np.mean(marks, axis=0)     # per subject

print("=== STUDENT AVERAGES ===")
for i, name in enumerate(students):
    print(f"  {name:8s}: {student_avg[i]:.1f}  (std: {student_std[i]:.1f})")

print("\n=== SUBJECT AVERAGES ===")
for i, subj in enumerate(subjects):
    print(f"  {subj:10s}: {subject_avg[i]:.1f}")

# ── STEP 2: Grade Assignment using np.where ───────
def assign_grade(avg):
    return np.where(avg >= 90, 'A',
           np.where(avg >= 80, 'B',
           np.where(avg >= 70, 'C',
           np.where(avg >= 60, 'D', 'F'))))

grades = assign_grade(student_avg)
print("\n=== GRADES ===")
for i, name in enumerate(students):
    print(f"  {name:8s}: {grades[i]}  ({student_avg[i]:.1f})")

# ── STEP 3: Rankings ──────────────────────────────
rank_order = np.argsort(student_avg)[::-1]  # descending
print("\n=== STUDENT RANKINGS ===")
for rank, idx in enumerate(rank_order, 1):
    print(f"  #{rank}. {students[idx]:8s}: {student_avg[idx]:.1f}")

# ── STEP 4: Identify At-Risk Students ─────────────
at_risk = student_avg < 60
print("\n=== AT-RISK STUDENTS ===")
at_risk_names = [students[i] for i in np.where(at_risk)[0]]
print(f"  {at_risk_names}")

# ── STEP 5: Score Normalization (0-100 scale) ─────
# Min-max normalize each subject independently
col_min = marks.min(axis=0)
col_max = marks.max(axis=0)
normalized = (marks - col_min) / (col_max - col_min) * 100
print("\n=== NORMALIZED SCORES (first 3 students) ===")
print(np.round(normalized[:3], 1))

# ── STEP 6: Class-wide summary ────────────────────
print("\n=== CLASS SUMMARY ===")
print(f"  Overall average: {np.mean(marks):.1f}")
print(f"  Pass rate:       {(student_avg >= 60).mean()*100:.0f}%")
print(f"  Top scorer:      {students[np.argmax(student_avg)]}")
print(f"  Hardest subject: {subjects[np.argmin(subject_avg)]}")
print(f"  Easiest subject: {subjects[np.argmax(subject_avg)]}")

# ── STEP 7: Correlation between subjects ──────────
corr_matrix = np.corrcoef(marks.T)  # .T gives subject-subject corr
print(f"\n  Math-CS correlation: {corr_matrix[0,3]:.3f}")  # expect high

=== STUDENT AVERAGES ===
  Ali     : 86.4  (std: 6.7)
  Sara    : 78.4  (std: 8.1)
  Hamza   : 59.6  (std: 7.7)
  Ayesha  : 92.8  (std: 3.4)
  Usman   : 46.0  (std: 6.6)
  Zara    : 80.6  (std: 4.4)
  Bilal   : 67.0  (std: 4.2)
  Fatima  : 84.8  (std: 4.0)

=== SUBJECT AVERAGES ===
  Math      : 71.9
  Physics   : 73.9
  Chem      : 72.8
  CS        : 77.1
  Eng       : 76.6

=== GRADES ===
  Ali     : B  (86.4)
  Sara    : C  (78.4)
  Hamza   : F  (59.6)
  Ayesha  : A  (92.8)
  Usman   : F  (46.0)
  Zara    : B  (80.6)
  Bilal   : D  (67.0)
  Fatima  : B  (84.8)

=== STUDENT RANKINGS ===
  #1. Ayesha  : 92.8
  #2. Ali     : 86.4
  #3. Fatima  : 84.8
  #4. Zara    : 80.6
  #5. Sara    : 78.4
  #6. Bilal   : 67.0
  #7. Hamza   : 59.6
  #8. Usman   : 46.0

=== AT-RISK STUDENTS ===
  ['Hamza', 'Usman']

=== NORMALIZED SCORES (first 3 students) ===
[[ 87.3  70.4 100.   94.3  76.9]
 [ 58.2  87.   46.5  84.9  64.1]
 [ 27.3  40.7   0.   47.2  33.3]]

=== CLASS SUMMARY ===
  Overall average: 7